name: ditumbas
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.10+1
  flutter_launcher_icons: ^0.10.0
  flutter_inappwebview: ^5.4.3+7
  url_launcher: ^6.1.6
  internet_connection_checker: ^1.0.0+1
  provider: ^6.0.3
  smooth_page_indicator: ^1.0.0+2
  firebase_core: ^1.24.0
  firebase_messaging: ^13.0.4
  flutter_local_notifications: ^12.0.0
  intl: ^0.17.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 19
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon_foreground.png"
  web:
    generate: false
  windows:
    generate: false

flutter:
  uses-material-design: true
  assets:
  - assets/